#!/usr/bin/env bash

set -ex

if [[ $# -lt 1 ]]; then
  echo "Expecting at least a runner name as first argument"
  exit 2
fi

RUNNER_NAME=$1
shift 1

docker run --rm -it \
  -v gitlab-runner-config-"$RUNNER_NAME":/etc/gitlab-runner \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --link gitlab:gitlab.localhost \
  gitlab/gitlab-runner:latest \
  -- register \
  --executor docker \
  --name runner-"$RUNNER_NAME" \
  --url http://gitlab.localhost/ \
  --docker-image "ubuntu:18.04" \
  --docker-links gitlab:gitlab.localhost \
  --docker-volumes '/var/run/docker.sock:/var/run/docker.sock' \
  --docker-privileged \
  --env "DOCKER_TLS_CERTDIR=" \
