platform: linux
image_resource:
    type: docker-image
    source:
        repository: nexus:8083/node
        tag: 10.16.3-stretch
        insecure_registries: [ "nexus:8083" ]

inputs:
  - name: ci
  - name: src
outputs:
  - name: node_modules
caches:
  - path: node_modules

run:
    path: ci/scripts/npm-install.sh
params:
    NPM_CONFIG_REGISTRY: http://nexus:8081/repository/npm-all/
